on: push

name: Publish stories if changed
jobs:
  checkChangesInStories:
    name: Check changes in stories
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: Jitender46559/python-code-review@master
