on: push
name: Publish stories if changed
jobs:
  checkChangesInStories:
    name: Check changes in stories
    runs-on: ubuntu-latest
    steps:
    - run: |
        git status
        git diff-index --quiet HEAD~$(jq '.commits | length' "${GITHUB_EVENT_PATH}") -- $*
    - name: Check changes in stories
      uses: ./action
      with:
        args: src
