on: push
name: Publish stories if changed
jobs:
  checkChangesInStories:
    name: Check changes in stories
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check changes in stories
      uses: open-sauced/diff-includes@master
      with:
        args: docs
