on: 
  push:
    paths: "src/**"
name: Publish stories if changed
jobs:
  checkChangesInStories:
    name: Check changes in stories
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Ship changes in stories
      uses: ./action
      with:
        args: src
