name: Resize images

on: push

jobs:
  resize-images:
    name: resize image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Image Resizer Action
      uses: sharadcodes/img-resizer@v1.0
      with:
        image-folder: 'topics/*/' # This is a Required field & this folder has original images
        new-resolution: '288x288' # This is Required field
        output-folder: "topics/*/" # This is Required field & this folder will be used to store resized images
    - name: Add & Commit files
      run: |
        git config --local user.email "github-action[bot]@github.com"
        git config --local user.name "GitHub Action Bot"
        git add .
        git commit -m "Add changes" -a
        git push -f -q https://${{ secrets.GITHUB_TOKEN }}@github.com/bdougie/bot-test-repo.git master    
