name: Resize images

on: 
  push:
    paths:
      - 'topics/**/**.png'
  pull_request:
    paths:
      - 'topics/**/**.png'

jobs:
  resize-images:
    name: resize image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Image Resizer to 288x288
      run: convert explore.png -resize 288x288 explore.png
    - name: Add & Commit files
      run: |
        git config --local user.email "github-action[bot]@github.com"
        git config --local user.name "GitHub Action Bot"
        git add .
        git commit -m "Add changes" -a
        git push -f -q https://${{ secrets.GITHUB_TOKEN }}@github.com/bdougie/bot-test-repo.git master    
