on: issues
name: Marky Markdown
jobs:
  markdown:
  - name: markdown-marker
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: bdougie/variables-in-markdown@v0.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
