on: issues
name: Marky Markdown
jobs:
  markdown:
    name: markdown-marker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: bdougie/variables-in-markdown@master
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

