on: issues
name: Marky Markdown
jobs:
  markdown:
    name: markdown-marker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: variables in markdwon
      uses: bdougie/variables-in-markdown@master
