name: Label Test
on:
  issues:
    types: [labeled, unlabeled]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const res = await github.issues.listForRepo(
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                assignee: "*"
              }
            )
            
            res.data.forEach((x) => {
              octokit.issues.listEvents({
                owner,
                repo,
                x.number
              }).then((event) => console.log(event)).catch((error) => console.log("ERROR: " + error));
                          
              // await github.issues.createComment({
                // issue_number: x.number,
                // owner: context.repo.owner,
                // repo: context.repo.repo,
                // body: 'Hey, you gonna eat this?'
              // })

            }
