name: "Label Top 5"
on:
  issues:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["Top 5"]'
          labels: '["top5"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: pin an issue
        uses: bdougie/issue-pin-by-label@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL_NAME: top5
