name: Label Test
on:
  issues:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/github-script@0.8.0
        env: 
          GITHUB_TOKEN: ${{ secrets.BDOUGIE_TOKEN }}
        with:
          script: |
            console.log(github.issues.list())
