name: Look for linked issues

on:
  workflow_dispatch:

jobs:
  linked-issues:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/github-script@v3
        id: first
        name: Script to find linked issues
        with:
          github-token: ${{secrets.GITHUB_TOKEN}} 
          script: |
            const response = await github.issues.listEventsForTimeline({issue_number: 823, owner: "open-sauced", repo: "open-sauced"});

            let fin = [];
            const filteredResp = response.data.filter((d) => {
                return d.event === "cross-referenced"
            }).reduce((res, x) => {
                // console.log(x)
                return fin.push(x.source.issue.number);
            }, [])
            
            console.log(fin);

            // return fin;
            
            github.issues.createComment({
              issue_number: fin[0],
              owner: "open-sauced",
              repo: "open-sauced",
              body: `👋 Thanks for link!`
            })
        
#       - run: Label the PR
#       - uses: actions/github-script@v3
#         name: label pull requests
#         with:
#           github-token: ${{secrets.GITHUB_TOKEN}}
#           script: |
#             github.issues.createComment({
#               issue_number: context.issue.number,
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               body: `👋 Thanks for link! ${steps.first.outputs.result[0]}`
#             })
        
