name: Take care of linked issues

on:
  issue_comment:
    types: [created, edited]

jobs:
  linked-issues:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/github-script@v3
        name: Script to find linked issues
        with:
          script: |
            const response = await github.issues.listEventsForTimeline({issue_number: 689, owner: "open-sauced", repo: "open-sauced"});

            let fin = [];
            const filteredResp = response.data.filter((d) => {
                return d.event === "cross-referenced"
            }).reduce((res, x) => {
                // console.log(x)
                return fin.push(x.source.issue.number);
            })

            console.log(fin);
