name: R U THERE

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo ${{ GITHUB_CONTEXT }}
