on:
  schedule:
  - cron: 15 * * * 2
name: Weekly Meeting
jobs:
  cycle-weekly-meeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: cycle-weekly-meeting
      uses: ./action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
