name: Scrape test
on:
  issues:
    types: [labeled, unlabeled]
#   schedule:
#     - cron:  '0 * * * *' # Every hour. Ref https://crontab.guru/examples.html

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: npm install
    - name: Scrape
      uses: notBdougie/issues-to-data@master
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
