name: Take Actions
on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  take-issue:
    runs-on: ubuntu-latest
    steps:
      - run: |
          string="My long string"
          if [[ "$(echo "$string")" == *"My long"* ]]; then
            echo "It's there!"
          fi
      - name: take an issue
        uses: bdougie/take--action@debug
