name: Assign
on:
  issue_comment:
    types: [created, edited]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: take an issue
        uses: bdougie/take-action@main
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
