name: Assign
on:
  issue_comment:
    types: [created, edited]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_EVENT_PATH
      - name: take an issue
        uses: bdougie/take-action@main
